import React, { useState, useEffect } from "react";
import styled from "styled-components";
import { CircularProgress } from "@mui/material";
import SearchBar from "../components/SearchBar";
import ImageCard from "../components/ImageCard";
import { getPosts } from "../api";

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
  width: 100%;
`;

const HeadingSection = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  text-align: center;
`;

const Heading = styled.h1`
  font-size: 32px;
  font-weight: 700;
  color: ${({ theme }) => theme.text.primary};
  letter-spacing: -0.5px;

  span {
    background: linear-gradient(135deg, ${({ theme }) => theme.yellow}, #f7e98e);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }

  @media (max-width: 768px) {
    font-size: 24px;
  }
`;

const SubHeading = styled.p`
  font-size: 15px;
  color: ${({ theme }) => theme.text.secondary};
  max-width: 500px;
  line-height: 1.5;
`;

const ImageGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
  width: 100%;

  & > div:nth-child(7n + 1) {
    grid-column: auto / span 2;
    grid-row: auto / span 2;
  }

  @media (max-width: 1200px) {
    grid-template-columns: repeat(3, 1fr);
  }

  @media (max-width: 768px) {
    grid-template-columns: repeat(2, 1fr);

    & > div:nth-child(7n + 1) {
      grid-column: auto / span 1;
      grid-row: auto / span 1;
    }
  }

  @media (max-width: 480px) {
    grid-template-columns: 1fr;
  }
`;

const LoadingContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 16px;
  padding: 60px 0;
`;

const LoadingText = styled.p`
  font-size: 14px;
  color: ${({ theme }) => theme.text.secondary};
`;

const EmptyState = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 0;
  gap: 12px;
`;

const EmptyText = styled.p`
  font-size: 18px;
  font-weight: 500;
  color: ${({ theme }) => theme.text.secondary};
`;

const EmptySubText = styled.p`
  font-size: 14px;
  color: ${({ theme }) => theme.text.secondary};
  opacity: 0.7;
`;

const Home = () => {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [filteredPosts, setFilteredPosts] = useState([]);

  useEffect(() => {
    const fetchPosts = async () => {
      try {
        setLoading(true);
        const res = await getPosts();
        setPosts(res.data.data);
        setFilteredPosts(res.data.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, []);

  useEffect(() => {
    if (!search) {
      setFilteredPosts(posts);
      return;
    }
    const searchLower = search.toLowerCase();
    const filtered = posts.filter(
      (post) =>
        post.name.toLowerCase().includes(searchLower) ||
        post.prompt.toLowerCase().includes(searchLower)
    );
    setFilteredPosts(filtered);
  }, [search, posts]);

  return (
    <Container>
      <HeadingSection>
        <Heading>
          Explore posts generated with <span>AI</span>
        </Heading>
        <SubHeading>
          Browse through a collection of stunning, visually appealing images
          generated by DALL-E AI
        </SubHeading>
      </HeadingSection>

      <SearchBar
        value={search}
        handleChange={(e) => setSearch(e.target.value)}
      />

      {loading ? (
        <LoadingContainer>
          <CircularProgress
            sx={{ color: "#e8d44d" }}
            size={40}
          />
          <LoadingText>Loading posts...</LoadingText>
        </LoadingContainer>
      ) : filteredPosts.length === 0 ? (
        <EmptyState>
          <EmptyText>No Posts Found</EmptyText>
          <EmptySubText>
            {search
              ? "Try a different search term"
              : "Be the first to create an AI-generated image!"}
          </EmptySubText>
        </EmptyState>
      ) : (
        <ImageGrid>
          {filteredPosts.map((post) => (
            <ImageCard key={post._id} item={post} />
          ))}
        </ImageGrid>
      )}
    </Container>
  );
};

export default Home;
